# Dimensionality Reduction

# 2. DATA PREP

In [1]:
import pandas as pd
import numpy as np
absence = pd.read_csv("Absenteeism_at_work_2.csv", sep = ';')
import matplotlib.pyplot as plt
absence.head()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance to Work,Service time,Age,Work load per day,...,Disc failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2

In [2]:
absence["Work load per day"] = absence["Work load per day"].replace(
    [246.288, 241.476, 251.818, 236.629, 377.550, 313.532, 265.017, 294.217, 284.853, 246.074],
    [np.nan, np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan ])
absence["Service time"] = absence["Service time"].replace(
    [3,6,7,8,9,11,13, 18, 22, 29],
    [np.nan, np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan ])

In [3]:
df1 = absence.loc[:, ['Reason for absence', 'Month of absence', 'Day of the week', 
                      'Seasons','Transportation expense', 'Distance to Work', 'Service time', 'Age', 'Work load per day', 
                     'Education','Son', 'Social drinker', 'Social smoker', 'Weight', 'Height', 'Body mass index', 
                     'Absenteeism time in hours']]

In [4]:
df1.to_csv("absence_data.csv")

In [5]:
df1.isna().any()

Reason for absence           False
Month of absence             False
Day of the week              False
Seasons                      False
Transportation expense       False
Distance to Work             False
Service time                  True
Age                          False
Work load per day             True
Education                    False
Son                          False
Social drinker               False
Social smoker                False
Weight                       False
Height                       False
Body mass index              False
Absenteeism time in hours    False
dtype: bool

# we might want to add
- AIC
- forward/backward procedures (but are model-dependent)